print('Website ban hang online')
print('add frontend template')
print('add new css template')
print('add show product')
print('show list')
print('show list')
print('add config list')
print('fi config list')
print('add config list')
print('fi config list')
print('test')
print('test list')
print('display result')
print('show list')
print('show list')


